# sit722-10-3hd/k8s/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product_service:8000']
  
  - job_name: 'order-service'
    static_configs:
      - targets: ['order_service:8000']

  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer_service:8000']